### ISSUE TITLE
BoxConstraints has a negative minimum height.

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [NikitaZhelonkin/FlutterScrollingPageIndicator#3]
> When the exception was thrown, this was the stack: 
> #0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError (package:flutter/src/rendering/box.dart:510:9)
> #1      BoxConstraints.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/box.dart:541:19)
> #2      BoxConstraints.debugAssertIsValid (package:flutter/src/rendering/box.dart:558:6)
> #3      new RenderConstrainedBox (package:flutter/src/rendering/proxy_box.dart:196:37)
> #4      SizedBox.createRenderObject (package:flutter/src/widgets/basic.dart:2077:12)
> 

This is thrown with the following code.

```dart
Stack(
            children: <Widget>[
              SizedBox.expand(
                child: PageView(
                  controller: _pageController,
                  scrollDirection: Axis.vertical,
                  children: state.pages,
                ),
              ),
              Positioned(
                right: 10,
                child: ScrollingPageIndicator(
                  orientation: Axis.vertical,
                  itemCount: state.pages.length, // which is 0 currently
                  controller: _pageController,
                ),
              )
            ],
          );
```

**Comment by NikitaZhelonkin** [comment]
Have no crash with your code. Seems the problem somewhere else

**Comment by ThinkDigitalSoftware** [comment]
Hmm. Ok. Maybe so. Thank you. I moved on and don't have an issue right now.
