### ISSUE TITLE
[Feature Request] Add labels 

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [NikitaZhelonkin/FlutterScrollingPageIndicator#4]
Hi, my design calls for labels to appear briefly when a new page is chosen.
Is that something that's easy to add? Fade in for a specified duration before disappearing. Thanks!

**Comment by NikitaZhelonkin** [comment]
Can you attach image? Don't understand what you mean

**Comment by ThinkDigitalSoftware** [comment]
![Screenshot_20190928-001027_Slides](https://user-images.githubusercontent.com/23037821/65813064-b0397900-e184-11e9-8b8a-40b8d11af6f5.jpg)
Sure. Something like this, but I would like the option to customize when it appears, like when the page is scrolled to, show some text for a certain duration, it would need a map or to accept a function to keep track of the labels for each indicator.

**Comment by NikitaZhelonkin** [comment]
I think u don't need FlutterScrollingPageIndicator to implement this. U have constant pages here and the same count of 'dots'. But the main feature of this package is to display pages more then count of dots

**Comment by ThinkDigitalSoftware** [comment]
Ok, I'll see what I can do, thank you
