### ISSUE TITLE
Change Animation Direction

### ISSUE THREAD

**Issue by YoussefGheith** [NikitaZhelonkin/FlutterScrollingPageIndicator#7]
Dear Nikita 

Firstly 
Thank you for this awesome package.
Secondly
Is there a way to change the direction  of the indicator animation from LTR to RTL ??

**Comment by NikitaZhelonkin** [comment]
I will add rtl support soon

**Comment by YoussefGheith** [comment]
much appreciated 
tnx

**Comment by NikitaZhelonkin** [comment]
I have just added rtl support in v0.1.3
add `reversed=true` param to `ScrollingPageIndicator`

**Comment by YoussefGheith** [comment]
Fantastic!!
