### ISSUE TITLE
Null-safety support?

### ISSUE THREAD

**Issue by DanMossa** [NikitaZhelonkin/FlutterScrollingPageIndicator#8]
Are there plans to support null-safety?
Thanks!

**Comment by redDwarf03** [comment]
try for the moment: https://github.com/redDwarf03/FlutterScrollingPageIndicator.git

**Comment by DanMossa** [comment]
Amazing!
Any specific reason for not making a pull request?
@redDwarf03

**Comment by redDwarf03** [comment]
I'm shy lol

**Comment by DanMossa** [comment]
No better way to learn than in an open source project :P
But of course do what you feel is comfortable! @redDwarf03

**Comment by redDwarf03** [comment]
PR done ;)

**Comment by redDwarf03** [comment]
my PR is sleeping since a long time...

**Comment by NikitaZhelonkin** [comment]
See comments in pull request

**Comment by bkraszewski** [comment]
Hey, can't see any PR comments, whats stopping us from merging this PR and releasing a new version? :)

**Comment by khangahs** [comment]
null-safety when?
